"""Build a self-contained Claude Desktop extension (``.mcpb``) for one target.

    uv run python scripts/build_mcpb.py [--target darwin-arm64|darwin-x64|win32-x64]

Each bundle carries its own CPython runtime (copied from uv's managed
interpreter dir), the locked dependency closure installed flat into
``server/lib``, and a generated ``manifest.json`` — the installing machine
needs no Python, no pip, no venv. The extension metadata's one home is the
``manifest()`` dict below (built per target, so JSON validity is
``json.dumps``'s problem, not a text template's).
``--target`` defaults to the host, and a foreign target is refused outright:
``uv python install`` only ever fetches the *host's* build, so cross-building
would silently bundle the wrong runtime. One bundle therefore means one native
run (in CI: one native runner per matrix leg — release.yml).

Stage layout, mirrored by the manifest the script writes:

    <stage>/
      manifest.json
      icon.png
      server/
        python/          # the whole interpreter; POSIX bin/ keeps ONLY the
                         # real binary (mcpb pack materialises symlinks into
                         # full ~18 MB copies), Windows keeps python.exe
        lib/             # the locked closure + the anafpy wheel, installed
                         # with --target; plus a generated sitecustomize.py
                         # that replays .pth files (pywin32 needs it — PYTHONPATH
                         # entries get no .pth processing of their own)

The interpreter version is the exact ``[tool.anafpy] bundle-python`` pin in
pyproject.toml; a loose pin fails the build. The dependency closure is
``uv export --frozen`` — installs pass ``--no-deps`` so nothing is re-resolved
past the lock, and ``--only-binary :all:`` so a missing wheel fails loudly
instead of becoming a source build against who-knows-which OpenSSL. The one
sanctioned exception is per-target: cryptography publishes no Intel-macOS
wheel since 49.0.0, so darwin-x64 builds it from the locked sdist (its CI leg
sets OPENSSL_DIR).
"""

from __future__ import annotations

import argparse
import json
import platform
import shutil
import subprocess
import tomllib
import zipfile
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Copied into the bundle as icon.png — the name the manifest declares.
ICON = ROOT / "imgs" / "anafpy-icon-512.png"
# Exact packer pin — the packer decides the archive layout.
MCPB_PACKER = "@anthropic-ai/mcpb@2.1.2"

# Interpreter flags, chosen deliberately (each rejected flag would break the
# bundle): -P keeps cwd off sys.path (the client spawns the server from an
# arbitrary directory), -s ignores the *user's* site-packages. Never -E or -I
# (they discard PYTHONPATH, which is how server/lib is found) and never -S
# (it skips `site`, which is what imports our sitecustomize).
PYTHON_FLAGS = ["-P", "-s"]

# server/lib joins sys.path via PYTHONPATH, which gets no .pth processing —
# addsitedir replays every .pth as if lib were a real site dir. pywin32 (in the
# closure via the MCP SDK on Windows) is unimportable without it: its modules
# and DLL registration live behind pywin32.pth. Written for every target — on
# POSIX there are no .pth files and it merely re-adds a known path — because a
# platform-conditional file is one more thing to get wrong.
SITECUSTOMIZE = '''\
"""Generated by scripts/build_mcpb.py — replay .pth files in server/lib."""

import os
import site

site.addsitedir(os.path.dirname(os.path.abspath(__file__)))
'''


@dataclass(frozen=True)
class Target:
    """One platform/arch bundle: what to stage and how the manifest launches it."""

    name: str
    platform: str  # manifest compatibility.platforms value
    interpreter: str  # staged path of the real binary, relative to server/python
    # Packages allowed to build from the locked sdist because the target has no
    # wheel. A per-target opt-in, never a global fallback: anywhere else a
    # missing wheel must fail the build, not silently compile against an
    # incompatible system library.
    sdist_packages: tuple[str, ...] = field(default=())


def _targets(python_minor: str) -> dict[str, Target]:
    posix_bin = f"bin/python{python_minor}"
    return {
        "darwin-arm64": Target("darwin-arm64", "darwin", posix_bin),
        "darwin-x64": Target(
            "darwin-x64", "darwin", posix_bin, sdist_packages=("cryptography",)
        ),
        "win32-x64": Target("win32-x64", "win32", "python.exe"),
    }


def host_target() -> str:
    """The only target this machine can build (see require_native)."""
    match (platform.system(), platform.machine()):
        case ("Darwin", "arm64"):
            return "darwin-arm64"
        case ("Darwin", "x86_64"):
            return "darwin-x64"
        case ("Windows", "AMD64"):
            return "win32-x64"
        case (system, machine):
            raise SystemExit(f"no bundle target for this host ({system}/{machine})")


def require_native(target: str) -> None:
    """Refuse a cross-build: uv would bundle the HOST's interpreter, silently."""
    if (host := host_target()) != target:
        raise SystemExit(
            f"cannot build {target} on a {host} host: `uv python install` only "
            "fetches the host's own CPython build, so the bundle would carry "
            "the wrong runtime. Build each target on its native machine."
        )


def _run(cmd: list[str], **kwargs: object) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, **kwargs)  # type: ignore[call-overload]


def _which(program: str) -> str:
    # shutil.which, not bare list-mode subprocess: on Windows `npx` is npx.cmd
    # and `uv` may be uv.exe — list-mode subprocess.run resolves neither.
    if path := shutil.which(program):
        return path
    raise SystemExit(f"`{program}` not found on PATH")


def read_pins() -> tuple[str, str]:
    """(project version, exact bundle CPython pin) from pyproject.toml."""
    with (ROOT / "pyproject.toml").open("rb") as fh:
        pyproject = tomllib.load(fh)
    version: str = pyproject["project"]["version"]
    pin: str = pyproject["tool"]["anafpy"]["bundle-python"]
    match pin.split("."):
        case [major, minor, patch] if all(p.isdigit() for p in (major, minor, patch)):
            return version, pin
        case _:
            raise SystemExit(
                f"[tool.anafpy] bundle-python = {pin!r} is not an exact X.Y.Z "
                "pin — a loose pin lets the release runners disagree on the "
                "interpreter they bundle."
            )


def stage_runtime(uv: str, pin: str, stage: Path, target: Target) -> Path:
    """Install the pinned CPython via uv and copy it whole into the stage."""
    try:
        _run([uv, "python", "install", pin])
    except subprocess.CalledProcessError:
        raise SystemExit(
            f"`uv python install {pin}` failed. If the version exists, the uv "
            "on PATH probably predates it — uv resolves interpreters against "
            "a manifest baked into its own binary, so upgrade uv."
        ) from None
    managed = Path(
        subprocess.run(
            [uv, "python", "dir"], check=True, capture_output=True, text=True
        ).stdout.strip()
    )
    # Exactly one match, asserted rather than picking [0]: a glob that suddenly
    # matches two dirs means the layout changed under us.
    match sorted(managed.glob(f"cpython-{pin}-*")):
        case [only]:
            src = only
        case matches:
            raise SystemExit(
                f"expected exactly one cpython-{pin}-* under {managed}, "
                f"found {[m.name for m in matches]}"
            )
    dest = stage / "server" / "python"
    # symlinks=True keeps the copy faithful; prune_runtime then deletes the
    # links so `mcpb pack` cannot materialise them into full copies.
    shutil.copytree(src, dest, symlinks=True)
    interpreter = dest / target.interpreter
    if not interpreter.is_file() or interpreter.is_symlink():
        raise SystemExit(f"staged interpreter {interpreter} is not a real file")
    return interpreter


def prune_runtime(python_dir: Path, target: Target) -> None:
    """Drop what the bundle must not ship (details in the module docstring)."""
    if target.platform == "win32":
        # Console-script shims full of build-machine paths; nothing uses them.
        shutil.rmtree(python_dir / "Scripts", ignore_errors=True)
        site_packages = python_dir / "Lib" / "site-packages"
    else:
        # Keep only the real binary: python/python3 are symlinks that `mcpb
        # pack` would materialise into ~18 MB copies each, and pip3 shims
        # carry the build machine's absolute paths.
        keep = python_dir / target.interpreter
        for entry in (python_dir / "bin").iterdir():
            if entry != keep:
                entry.unlink()
        # terminfo/man pages, and pkg-config metadata for embedders — dead
        # weight a stdio server never reads (pkgconfig also holds the two
        # symlinks left after bin/ is pruned; the audit refuses symlinks).
        shutil.rmtree(python_dir / "share", ignore_errors=True)
        shutil.rmtree(python_dir / "lib" / "pkgconfig", ignore_errors=True)
        (minor_dir,) = (python_dir / "lib").glob("python3.*")
        site_packages = minor_dir / "site-packages"
    # The runtime's own site-packages carries pip — which could only ever
    # install into the extension directory, exactly what must never happen.
    for entry in site_packages.iterdir() if site_packages.is_dir() else ():
        shutil.rmtree(entry) if entry.is_dir() else entry.unlink()


def install_closure(
    uv: str, interpreter: Path, lib: Path, build_dir: Path, target: Target
) -> None:
    """Vendor the locked closure + the project wheel flat into server/lib."""
    requirements = build_dir / "requirements.txt"
    # The export IS the complete locked closure (all extras: the user cannot
    # pip-install one afterwards), so both installs pass --no-deps — letting
    # uv re-resolve has been observed to pull versions the lock had moved off.
    _run(
        [
            uv,
            "export",
            "--frozen",
            "--no-dev",
            "--all-extras",
            "--no-emit-project",
            "--output-file",
            str(requirements),
        ],
        cwd=ROOT,
    )
    wheel_dir = build_dir / "wheel"
    _run([uv, "build", "--wheel", "--out-dir", str(wheel_dir)], cwd=ROOT)
    (wheel,) = wheel_dir.glob("anafpy-*.whl")

    # --python <staged interpreter>: wheel tags and environment markers must be
    # evaluated against the interpreter that ships, not the build venv.
    base = [
        uv,
        "pip",
        "install",
        "--python",
        str(interpreter),
        "--target",
        str(lib),
        "--no-deps",
        "--only-binary",
        ":all:",
    ]
    # uv follows pip's format-control semantics: a per-package --no-binary
    # carves an exception out of --only-binary :all: (verified: uv 0.12.2
    # builds the sdist for the excepted package even where a wheel exists).
    for package in target.sdist_packages:
        base += ["--no-binary", package]
    _run([*base, "--requirements", str(requirements)])
    _run([*base, str(wheel)])

    # Console-script shims generated with the build machine's absolute paths.
    shutil.rmtree(lib / "bin", ignore_errors=True)
    shutil.rmtree(lib / "Scripts", ignore_errors=True)
    (lib / "sitecustomize.py").write_text(SITECUSTOMIZE)


def manifest(version: str, target: Target) -> dict[str, object]:
    """The extension manifest, specialised for one target.

    This dict is the metadata's one home (the version rides in from
    pyproject.toml, so nothing re-states it). Field-by-field notes:

    - ``server.type`` is ``"binary"``, NOT ``"python"``: Claude Desktop derives
      the install dialog's requirements from this field, and ``"python"`` lists
      a system Python as an unmet requirement even though the bundle ships its
      own runtime.
    - ``compatibility`` declares the ONE platform the bundle is for, and no
      ``runtimes``: a binary bundle has no runtime requirements.
    - ``user_config`` types are the MCPB schema's — it has no enum/dropdown,
      so constrained values ride in descriptions and the server validates.
    """
    entry = f"server/python/{target.interpreter}"
    return {
        "manifest_version": "0.4",
        "name": "anafpy",
        "display_name": "anafpy — ANAF tools",
        "version": version,
        "description": (
            "Talk to Romania's ANAF tax authority: e-Factura inbox and filing, "
            "e-Transport declarations, SPV mailbox, tax declarations, and "
            "public registry lookups."
        ),
        "long_description": (
            "Local MCP server for ANAF's services — e-Factura (electronic "
            "invoicing), e-Transport (goods transport declarations), the SPV "
            "mailbox, tax declarations via ANAF's own DUKIntegrator validator, "
            "and the public no-auth lookups (taxpayer registry, VAT status, "
            "financial statements).\n\nThe extension is self-contained — it "
            "carries its own Python — and the public lookup tools work "
            "immediately after install, with no configuration. The "
            "authenticated e-Factura and e-Transport tools additionally need "
            "your own ANAF OAuth application (Client ID + Secret) and a "
            "one-time certificate login — once the settings below are filled "
            "in, just ask Claude to log you in to ANAF (your browser opens for "
            "the certificate step; roughly yearly). Every ANAF filing is "
            "two-step — the server prepares a preview and nothing is submitted "
            "until you explicitly approve it.\n\nThe workflow playbooks — "
            "declare an e-Transport from any document, prepare a tax "
            "declaration, summarize personal income — are served as same-name "
            "prompts, and are also available as Cowork Agent Skills from the "
            "plugin marketplace at github.com/robert-malai/anafpy.\n\nFull "
            "setup guide: https://anafpy.readthedocs.io/en/latest/mcp/setup/"
        ),
        "author": {
            "name": "Robert Malai",
            "url": "https://github.com/robert-malai",
        },
        "repository": {
            "type": "git",
            "url": "https://github.com/robert-malai/anafpy",
        },
        "homepage": "https://anafpy.readthedocs.io",
        "documentation": "https://anafpy.readthedocs.io/en/latest/mcp/setup/",
        "support": "https://github.com/robert-malai/anafpy/issues",
        "license": "Apache-2.0",
        "privacy_policies": ["https://anafpy.readthedocs.io/en/latest/privacy/"],
        "icon": "icon.png",
        "keywords": [
            "anaf",
            "e-factura",
            "e-transport",
            "spv",
            "romania",
            "tax",
            "invoicing",
        ],
        "server": {
            "type": "binary",
            "entry_point": entry,
            "mcp_config": {
                "command": "${__dirname}/" + entry,
                "args": [*PYTHON_FLAGS, "-m", "anafpy.mcp"],
                "env": {
                    "PYTHONPATH": "${__dirname}/server/lib",
                    "ANAFPY_CLIENT_ID": "${user_config.client_id}",
                    "ANAFPY_CLIENT_SECRET": "${user_config.client_secret}",
                    "ANAFPY_CIF": "${user_config.cif}",
                    "ANAFPY_REDIRECT_URI": "${user_config.redirect_uri}",
                    "ANAFPY_CURL": "${user_config.curl_path}",
                },
            },
        },
        "user_config": {
            "client_id": {
                "type": "string",
                "title": "ANAF Client ID",
                "description": (
                    "The Client ID of your own OAuth application on ANAF's "
                    "portal. Leave empty to use only the public lookup tools "
                    "— the setup guide explains how to register the "
                    "application."
                ),
                "required": False,
            },
            "client_secret": {
                "type": "string",
                "title": "ANAF Client Secret",
                "description": (
                    "The Client Secret shown next to the Client ID when the "
                    "application was registered. Stored in the system's "
                    "secure credential store."
                ),
                "sensitive": True,
                "required": False,
            },
            "cif": {
                "type": "string",
                "title": "Firm CUI (fiscal code)",
                "description": (
                    "Digits only, e.g. 12345678. Used as the default fiscal "
                    "code when a conversation doesn't say otherwise."
                ),
                "required": False,
            },
            "redirect_uri": {
                "type": "string",
                "title": "OAuth callback URL",
                "description": (
                    "Leave empty for the default, "
                    "https://localhost:9002/callback — the URL the setup "
                    "guide has you register. Fill in only if your ANAF "
                    "application registered a different Callback URL; it "
                    "must match that registration exactly."
                ),
                "required": False,
            },
            "curl_path": {
                "type": "string",
                "title": "curl program (Windows fix)",
                "description": (
                    "Full path to an alternative curl.exe, used by the SPV "
                    "and declaration-portal certificate logins. Needed only "
                    "on Windows with a broken built-in curl (versions "
                    "8.13–8.15) or on Windows-on-ARM — typically "  # noqa: RUF001
                    "C:\\Program Files\\Git\\mingw64\\bin\\curl.exe from Git "
                    "for Windows; the setup guide's troubleshooting table "
                    "has the details. Leave empty everywhere else."
                ),
                "required": False,
            },
        },
        "compatibility": {"platforms": [target.platform]},
    }


def write_manifest(stage: Path, version: str, target: Target) -> None:
    (stage / "manifest.json").write_text(
        json.dumps(manifest(version, target), indent=2, ensure_ascii=False) + "\n"
    )
    shutil.copy2(ICON, stage / "icon.png")


def pack(stage: Path, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.unlink(missing_ok=True)
    _run([_which("npx"), "--yes", MCPB_PACKER, "pack", str(stage), str(out)])


def audit(stage: Path, out: Path, target: Target) -> None:
    """Fail on the packing regressions that only show up on a user's machine."""
    with zipfile.ZipFile(out) as zf:
        names = set(zf.namelist())
        unpacked = sum(i.file_size for i in zf.infolist())
    expected = {
        "manifest.json",
        "icon.png",
        f"server/python/{target.interpreter}",
        "server/lib/sitecustomize.py",
        "server/lib/anafpy/__init__.py",
    }
    if missing := sorted(expected - names):
        raise SystemExit(f"packed archive is missing {missing}")
    # mcpb pack silently drops .env* at any depth and materialises symlinks
    # into full copies. The stage has neither (assert, don't hope): nothing
    # dotfile-shaped goes in, and prune_runtime removed every link — so the
    # unpacked size must track the staged size.
    staged_files = [p for p in stage.rglob("*") if p.is_file()]
    if links := [p for p in staged_files if p.is_symlink()]:
        raise SystemExit(f"stage still contains symlinks: {links[:5]}")
    staged = sum(p.stat().st_size for p in staged_files)
    if unpacked > staged * 1.05 + 1_000_000:
        raise SystemExit(
            f"packed contents ({unpacked:,} B) outgrew the stage ({staged:,} B) "
            "— mcpb pack most likely materialised a symlink into a full copy"
        )
    print(
        f"{out.name}: {out.stat().st_size:,} B packed, {unpacked:,} B unpacked, "
        f"{len(names)} files"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--target",
        choices=("darwin-arm64", "darwin-x64", "win32-x64"),
        # No default=host_target() here: that would refuse to even parse args
        # on a host with no target of its own (the Linux CI runner, which only
        # ever uses --manifests-only).
        default=None,
        help="bundle target; defaults to (and must equal) the host's own",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT / "mcpb-dist",
        help="where the packed .mcpb lands (default: mcpb-dist/)",
    )
    parser.add_argument(
        "--manifests-only",
        type=Path,
        metavar="DIR",
        help="write every target's generated manifest into DIR/<target>/"
        "manifest.json and exit. Manifest generation is pure — no native "
        "host, no uv — so CI schema-validates all three from one runner.",
    )
    args = parser.parse_args()

    version, pin = read_pins()
    minor = pin.rsplit(".", 1)[0]
    targets = _targets(minor)

    if args.manifests_only is not None:
        for target in targets.values():
            target_dir = args.manifests_only / target.name
            target_dir.mkdir(parents=True, exist_ok=True)
            (target_dir / "manifest.json").write_text(
                json.dumps(manifest(version, target), indent=2, ensure_ascii=False)
                + "\n"
            )
            # The validator resolves the manifest's icon path — ship it too.
            shutil.copy2(ICON, target_dir / "icon.png")
            print("wrote", target_dir / "manifest.json")
        return

    target = targets[args.target or host_target()]
    require_native(target.name)
    uv = _which("uv")

    build_dir = ROOT / "build" / "mcpb" / target.name
    stage = build_dir / "stage"
    shutil.rmtree(stage, ignore_errors=True)
    stage.mkdir(parents=True)

    interpreter = stage_runtime(uv, pin, stage, target)
    prune_runtime(stage / "server" / "python", target)
    install_closure(uv, interpreter, stage / "server" / "lib", build_dir, target)
    write_manifest(stage, version, target)

    out = args.out_dir / f"anafpy-{target.name}.mcpb"
    pack(stage, out)
    audit(stage, out, target)


if __name__ == "__main__":
    main()
